# Generated by Django 6.0.6 on 2026-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Housie Club', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('theme', models.CharField(default='light', max_length=20)),
                ('sound', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
        ),
    ]
